[package]
name = "password_cracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
md5 = "0.7.0"
sha2 = "0.10.6"
bcrypt = "0.13.0"
